### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by jihch** [whitefly/meaningOfLife#1]
我也不知道我为什么会在github上搜 "meaning of life"，你现在怎么样了？还好吗？我目前找到一个眼下可以凑合的答案——人生的意义大概是自己定义的，或者说信仰，你相信什么你人生的意义大概就是什么。
demo:
相信努力、奋斗，努力、奋斗之后大概就会充实起来，有所收获之后，大概也会有成就感；
相信友情看重朋友，大概就会为朋友付出然后收获友谊；
相信爱情大概就会收获爱情；
.......
依次类推
看你最近还在push，留个言给你看，世上人那么多，迷惘、困惑的不只你一个，你并不孤单

**Comment by whitefly** [comment]
谢谢同学你哈😺
19年处于心理低落期,甚至有一个月恍恍惚惚,整天想着离开这个让人难过的世界.
后来发现周围环境也不是想象的那么糟糕,还是存在一些可以值得盼望和奋斗的点.幸运的是2020年情况慢慢好转,现在日常看看有趣的开源代码,写一些和自身实际需求相关的项目,需要解决的问题越来越有挑战,对自身的价值感也逐渐上升.
虽然自身性格已经无法大改,有时候遇到新的难的东西还是会不自觉悲观,不过已经不像19年那个程度了.虽然很艰难,但已经开始选择相信:自己最终可以cover住它.
茫茫代码库中你可以搜到这个写于2年前的念念碎项目是缘分
祝同学你生活越来越好,技术越来越棒 \(^o^)/~
